# Generated by Django 5.0.6 on 2024-06-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        # migrations.RunSQL(open("init_triggers.sql").read())
    ]
