FROM postgres:13

# Установка дополнительных расширений или пакетов
RUN apt-get update && apt-get install -y \
    postgresql-contrib \
    && rm -rf /var/lib/apt/lists/*

# Копирование скриптов для инициализации базы данных
COPY init-db.sh /docker-entrypoint-initdb.d/

# Убедитесь, что скрипт имеет правильные права доступа
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh
